import { Suspense, lazy, useState } from 'react'
import { useShallow } from 'zustand/shallow'
import { useActivities } from '@/store/activities'
import { useFolders } from '@/store/folders'
import { DropZone } from '@/components/import/DropZone'
import { AutoOrganizeButton } from '@/components/import/AutoOrganizeButton'
import { DuplicateCleanupBanner } from '@/components/import/DuplicateCleanupBanner'
import { ActivityCard } from '@/components/layout/ActivityCard'
import { FolderHeader } from '@/components/layout/FolderHeader'
import { CollapsibleHeader } from '@/components/layout/CollapsibleHeader'
import { compareFolders, isBucketFolderName } from '@/lib/auto-organize'
import { getStoredTokens } from '@/lib/strava-auth'
import type { Activity, Folder } from '@/types'

// Pulls in the Strava OAuth/fetch flow, only relevant once this panel is
// actually opened — split out of the main bundle so it doesn't load on first paint.
const StravaImport = lazy(() => import('@/components/import/StravaImport').then((m) => ({ default: m.StravaImport })))

export function SortiesPanel({ onSelectActivity }: { onSelectActivity: () => void }) {
  const { activities, activeId, setActive, removeActivity, updateActivity, moveActivity, duplicateActivity } = useActivities(
    useShallow((s) => ({
      activities: s.activities,
      activeId: s.activeId,
      setActive: s.setActive,
      removeActivity: s.removeActivity,
      updateActivity: s.updateActivity,
      moveActivity: s.moveActivity,
      duplicateActivity: s.duplicateActivity,
    })),
  )
  const { folders, addFolder, renameFolder, deleteFolder } = useFolders(
    useShallow((s) => ({
      folders: s.folders,
      addFolder: s.addFolder,
      renameFolder: s.renameFolder,
      deleteFolder: s.deleteFolder,
    })),
  )
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set())
  const [creatingFolder, setCreatingFolder] = useState(false)
  const [newFolderName, setNewFolderName] = useState('')
  // Open by default only for a first-time/empty library — once there's
  // content, importing becomes the secondary action and the sync button +
  // folders should be what's visible without an extra tap.
  const [addOpen, setAddOpen] = useState(() => activities.length === 0)
  const [distanceGroupOpen, setDistanceGroupOpen] = useState(false)
  const [searchQuery, setSearchQuery] = useState('')
  // Read once, same tradeoff AutoOrganizeButton accepts — only used to show a
  // connection hint on the collapsed "Ajouter" header, not to gate any action.
  const [connected] = useState(() => getStoredTokens() !== null)

  const toggleFolder = (id: string) => {
    setExpandedFolders((s) => {
      const next = new Set(s)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  const unfiled = activities.filter((a) => !a.folderId)
  const sortedFolders = [...folders].sort(compareFolders)
  // Distance-bucket folders (auto-generated by "Organiser automatiquement")
  // are visually separated from folders named by hand — otherwise a ladder of
  // 15-20 "N-M km" entries buries whatever the user actually created themselves.
  const manualFolders = sortedFolders.filter((f) => !isBucketFolderName(f.name))
  const bucketFolders = sortedFolders.filter((f) => isBucketFolderName(f.name))
  const foldersTotal = activities.filter((a) => a.folderId).length

  const query = searchQuery.trim().toLowerCase()
  const searchResults = query ? activities.filter((a) => a.name.toLowerCase().includes(query)) : null

  const cardProps = (a: Activity) => ({
    activity: a,
    active: a.id === activeId,
    folders,
    onSelect: () => { setActive(a.id); onSelectActivity() },
    onDelete: () => removeActivity(a.id),
    onRename: (name: string) => updateActivity({ ...a, name }),
    onMove: (folderId: string | null) => moveActivity(a.id, folderId),
    onDuplicate: () => duplicateActivity(a.id),
  })

  const renderFolder = (f: Folder) => {
    const folderActivities = activities.filter((a) => a.folderId === f.id)
    const expanded = expandedFolders.has(f.id)
    return (
      <div key={f.id}>
        <FolderHeader
          folder={f}
          count={folderActivities.length}
          expanded={expanded}
          onToggle={() => toggleFolder(f.id)}
          onRename={(name) => renameFolder(f.id, name)}
          onDelete={() => deleteFolder(f.id)}
        />
        {expanded && (
          <div className="space-y-1.5 pl-3 pb-1.5">
            {folderActivities.length === 0 ? (
              <p className="text-[10px] text-[var(--color-text-muted)] px-1 pb-1">Vide</p>
            ) : (
              folderActivities.map((a) => <ActivityCard key={a.id} {...cardProps(a)} />)
            )}
          </div>
        )}
      </div>
    )
  }

  return (
    <div className="px-3 py-3 space-y-3">
      <div>
        <CollapsibleHeader
          label="Ajouter des sorties"
          expanded={addOpen}
          onToggle={() => setAddOpen((v) => !v)}
          badge={connected ? 'Strava connecté' : undefined}
        />
        {addOpen && (
          <div className="space-y-1 pt-1">
            <DropZone />
            <Suspense fallback={null}>
              <StravaImport />
            </Suspense>
          </div>
        )}
      </div>

      <AutoOrganizeButton />
      <DuplicateCleanupBanner />

      {activities.length > 0 && (
        <input
          type="search"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          placeholder="Rechercher une sortie…"
          className="w-full text-xs bg-[var(--color-surface-2)] border border-[var(--color-border)] rounded-lg px-3 min-h-11 outline-none text-[var(--color-text-primary)] placeholder:text-[var(--color-text-muted)]"
        />
      )}

      {searchResults ? (
        <div className="space-y-1.5">
          <p className="text-[10px] text-[var(--color-text-muted)] font-medium uppercase tracking-wider px-1">
            {searchResults.length} résultat{searchResults.length === 1 ? '' : 's'}
          </p>
          {searchResults.length === 0 ? (
            <p className="text-xs text-[var(--color-text-muted)] text-center mt-4">Aucune sortie ne correspond.</p>
          ) : (
            searchResults.map((a) => <ActivityCard key={a.id} {...cardProps(a)} />)
          )}
        </div>
      ) : (
        <>
          <div className="space-y-0.5">
            <div className="flex items-center justify-between px-1">
              <p className="text-[10px] text-[var(--color-text-muted)] font-medium uppercase tracking-wider">
                Dossiers
                {foldersTotal > 0 && (
                  <span className="text-[var(--color-text-muted)] font-normal normal-case"> · {foldersTotal} sortie{foldersTotal === 1 ? '' : 's'}</span>
                )}
              </p>
              <button
                onClick={() => { setCreatingFolder(true); setNewFolderName('') }}
                className="text-[10px] text-[var(--color-accent-hover)] hover:text-[var(--color-text-primary)] min-h-11 px-2.5 flex items-center -my-2"
              >
                + Nouveau
              </button>
            </div>

            {creatingFolder && (
              <input
                autoFocus
                value={newFolderName}
                onChange={(e) => setNewFolderName(e.target.value)}
                onBlur={() => {
                  const trimmed = newFolderName.trim()
                  if (trimmed) addFolder(trimmed)
                  setCreatingFolder(false)
                }}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') {
                    const trimmed = newFolderName.trim()
                    if (trimmed) addFolder(trimmed)
                    setCreatingFolder(false)
                  }
                  if (e.key === 'Escape') setCreatingFolder(false)
                }}
                placeholder="Nom du dossier"
                className="w-full text-xs bg-[var(--color-surface-2)] border border-[var(--color-accent)] rounded px-2 py-1.5 outline-none text-[var(--color-text-primary)]"
              />
            )}

            {manualFolders.map(renderFolder)}

            {bucketFolders.length > 0 && (
              <div>
                <CollapsibleHeader
                  label="Par distance"
                  badge={`${bucketFolders.length} tranche${bucketFolders.length === 1 ? '' : 's'}`}
                  expanded={distanceGroupOpen}
                  onToggle={() => setDistanceGroupOpen((v) => !v)}
                />
                {distanceGroupOpen && (
                  <div className="pl-3 space-y-0.5">
                    {bucketFolders.map(renderFolder)}
                  </div>
                )}
              </div>
            )}
          </div>

          <div className="space-y-1.5">
            {folders.length > 0 && (
              <p className="text-[10px] text-[var(--color-text-muted)] font-medium uppercase tracking-wider px-1">Non classées</p>
            )}
            {activities.length === 0 ? (
              <p className="text-xs text-[var(--color-text-muted)] text-center mt-4">
                Aucune sortie importée
              </p>
            ) : unfiled.length === 0 && folders.length > 0 ? (
              <p className="text-[10px] text-[var(--color-text-muted)] px-1">Aucune</p>
            ) : (
              unfiled.map((a) => <ActivityCard key={a.id} {...cardProps(a)} />)
            )}
          </div>
        </>
      )}
    </div>
  )
}
