import { Suspense, lazy, useState } from 'react'
import { useShallow } from 'zustand/shallow'
import { useActivities } from '@/store/activities'
import { useFolders } from '@/store/folders'
import { DropZone } from '@/components/import/DropZone'
import { AutoOrganizeButton } from '@/components/import/AutoOrganizeButton'
import { DuplicateCleanupBanner } from '@/components/import/DuplicateCleanupBanner'
import { ActivityCard } from '@/components/layout/ActivityCard'
import { FolderHeader } from '@/components/layout/FolderHeader'
import { compareFolders, isBucketFolderName } from '@/lib/auto-organize'
import type { Activity, Folder } from '@/types'
import clsx from 'clsx'

// Pulls in the Strava OAuth/fetch flow, only relevant once this panel is
// actually opened — split out of the main bundle so it doesn't load on first paint.
const StravaImport = lazy(() => import('@/components/import/StravaImport').then((m) => ({ default: m.StravaImport })))

export function SortiesPanel({ onSelectActivity }: { onSelectActivity: () => void }) {
  const { activities, activeId, setActive, removeActivity, updateActivity, moveActivity, duplicateActivity } = useActivities(
    useShallow((s) => ({
      activities: s.activities,
      activeId: s.activeId,
      setActive: s.setActive,
      removeActivity: s.removeActivity,
      updateActivity: s.updateActivity,
      moveActivity: s.moveActivity,
      duplicateActivity: s.duplicateActivity,
    })),
  )
  const { folders, addFolder, renameFolder, deleteFolder } = useFolders(
    useShallow((s) => ({
      folders: s.folders,
      addFolder: s.addFolder,
      renameFolder: s.renameFolder,
      deleteFolder: s.deleteFolder,
    })),
  )
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set())
  const [creatingFolder, setCreatingFolder] = useState(false)
  const [newFolderName, setNewFolderName] = useState('')

  const toggleFolder = (id: string) => {
    setExpandedFolders((s) => {
      const next = new Set(s)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  const unfiled = activities.filter((a) => !a.folderId)
  const sortedFolders = [...folders].sort(compareFolders)
  // Distance-bucket folders (auto-generated by "Organiser automatiquement")
  // render as a compact 2-column grid instead of full-width rows — a ladder
  // of 8+ tranches takes half the vertical space that way. Folders named by
  // hand keep the regular row treatment.
  const manualFolders = sortedFolders.filter((f) => !isBucketFolderName(f.name))
  const bucketFolders = sortedFolders.filter((f) => isBucketFolderName(f.name))
  const folderCounts = new Map(sortedFolders.map((f) => [f.id, activities.filter((a) => a.folderId === f.id).length]))
  const maxFolderCount = Math.max(1, ...folderCounts.values())
  const foldersTotal = activities.filter((a) => a.folderId).length
  const expandedBucketFolders = bucketFolders.filter((f) => expandedFolders.has(f.id))

  const cardProps = (a: Activity) => ({
    activity: a,
    active: a.id === activeId,
    folders,
    onSelect: () => { setActive(a.id); onSelectActivity() },
    onDelete: () => removeActivity(a.id),
    onRename: (name: string) => updateActivity({ ...a, name }),
    onMove: (folderId: string | null) => moveActivity(a.id, folderId),
    onDuplicate: () => duplicateActivity(a.id),
  })

  const renderFolderDetail = (f: Folder) => {
    const folderActivities = activities.filter((a) => a.folderId === f.id)
    return (
      <div key={f.id}>
        <FolderHeader
          folder={f}
          count={folderActivities.length}
          weight={folderActivities.length / maxFolderCount}
          expanded
          onToggle={() => toggleFolder(f.id)}
          onRename={(name) => renameFolder(f.id, name)}
          onDelete={() => deleteFolder(f.id)}
        />
        <div className="space-y-1.5 pl-3 pb-1.5">
          {folderActivities.length === 0 ? (
            <p className="text-[10px] text-[var(--color-text-muted)] px-1 pb-1">Vide</p>
          ) : (
            folderActivities.map((a) => <ActivityCard key={a.id} {...cardProps(a)} />)
          )}
        </div>
      </div>
    )
  }

  return (
    <div className="px-3 py-3 space-y-3">
      <DropZone />
      <Suspense fallback={null}>
        <StravaImport />
      </Suspense>
      <AutoOrganizeButton />
      <DuplicateCleanupBanner />

      <div className="space-y-0.5">
        <div className="flex items-center justify-between px-1">
          <p className="text-[10px] text-[var(--color-text-muted)] font-medium uppercase tracking-wider">
            Dossiers
            {foldersTotal > 0 && (
              <span className="text-[var(--color-text-muted)] font-normal normal-case"> · {foldersTotal} sortie{foldersTotal === 1 ? '' : 's'}</span>
            )}
          </p>
          <button
            onClick={() => { setCreatingFolder(true); setNewFolderName('') }}
            className="text-[10px] text-[var(--color-accent-hover)] hover:text-[var(--color-text-primary)] min-h-11 px-2.5 flex items-center -my-2"
          >
            + Nouveau
          </button>
        </div>

        {creatingFolder && (
          <input
            autoFocus
            value={newFolderName}
            onChange={(e) => setNewFolderName(e.target.value)}
            onBlur={() => {
              const trimmed = newFolderName.trim()
              if (trimmed) addFolder(trimmed)
              setCreatingFolder(false)
            }}
            onKeyDown={(e) => {
              if (e.key === 'Enter') {
                const trimmed = newFolderName.trim()
                if (trimmed) addFolder(trimmed)
                setCreatingFolder(false)
              }
              if (e.key === 'Escape') setCreatingFolder(false)
            }}
            placeholder="Nom du dossier"
            className="w-full text-xs bg-[var(--color-surface-2)] border border-[var(--color-accent)] rounded px-2 py-1.5 outline-none text-[var(--color-text-primary)]"
          />
        )}

        {manualFolders.map((f) => {
          const expanded = expandedFolders.has(f.id)
          return expanded ? renderFolderDetail(f) : (
            <FolderHeader
              key={f.id}
              folder={f}
              count={folderCounts.get(f.id) ?? 0}
              weight={(folderCounts.get(f.id) ?? 0) / maxFolderCount}
              expanded={false}
              onToggle={() => toggleFolder(f.id)}
              onRename={(name) => renameFolder(f.id, name)}
              onDelete={() => deleteFolder(f.id)}
            />
          )
        })}

        {bucketFolders.length > 0 && (
          <div className="grid grid-cols-2 gap-1.5 pt-0.5">
            {bucketFolders.map((f) => {
              const count = folderCounts.get(f.id) ?? 0
              const weight = count / maxFolderCount
              const expanded = expandedFolders.has(f.id)
              return (
                <button
                  key={f.id}
                  onClick={() => toggleFolder(f.id)}
                  className={clsx(
                    'relative overflow-hidden rounded-lg border px-2.5 py-2 text-left transition-colors min-h-11',
                    expanded
                      ? 'border-[var(--color-accent)]/50 bg-[var(--color-accent-soft)]'
                      : 'border-[var(--color-border)] bg-[var(--color-surface-1)] hover:border-[var(--color-text-muted)]',
                  )}
                >
                  <div
                    className="absolute inset-y-0 left-0 bg-[var(--color-accent)]/10"
                    style={{ width: `${Math.round(weight * 100)}%` }}
                    aria-hidden="true"
                  />
                  <span className="relative block text-[10px] font-bold text-[var(--color-text-secondary)] truncate">{f.name}</span>
                  <span className="relative block text-base font-bold text-[var(--color-accent)] leading-tight mt-0.5">{count}</span>
                  <span className="relative block text-[9px] text-[var(--color-text-muted)]">sortie{count === 1 ? '' : 's'}</span>
                </button>
              )
            })}
          </div>
        )}

        {expandedBucketFolders.length > 0 && (
          <div className="pt-1 space-y-0.5">
            {expandedBucketFolders.map(renderFolderDetail)}
          </div>
        )}
      </div>

      <div className="space-y-1.5">
        {folders.length > 0 && (
          <p className="text-[10px] text-[var(--color-text-muted)] font-medium uppercase tracking-wider px-1">Non classées</p>
        )}
        {activities.length === 0 ? (
          <p className="text-xs text-[var(--color-text-muted)] text-center mt-4">
            Aucune sortie importée
          </p>
        ) : unfiled.length === 0 && folders.length > 0 ? (
          <p className="text-[10px] text-[var(--color-text-muted)] px-1">Aucune</p>
        ) : (
          unfiled.map((a) => <ActivityCard key={a.id} {...cardProps(a)} />)
        )}
      </div>
    </div>
  )
}
